name: Build nRF52

on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARM_GNU_LINK: https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi.tar.xz
      ARM_GNU_ROOT: "${{ github.workspace }}/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Install dependencies 🔧
        run: sudo apt update && sudo apt install -y build-essential wget xz-utils

      - name: Cache ARM GNU Toolchain 💾
        id: cache-arm-toolchain
        uses: actions/cache@v4
        with:
          path: ${{ env.ARM_GNU_ROOT }}
          key: arm-gcc-${{ runner.os }}-14.2.rel1

      - name: Download ARM GNU Toolchain 🔽
        if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
        run: |
          wget -q --tries 3 ${{ env.ARM_GNU_LINK }} -O arm-toolchain.tar.xz
          tar -xf arm-toolchain.tar.xz
        working-directory: "${{ github.workspace }}"

      - name: Verify toolchain version 🧩
        run: |
          export PATH=${{ env.ARM_GNU_ROOT }}/bin:$PATH
          arm-none-eabi-ld --version

      - name: Build nRF52 project 🧱
        run: |
          export PATH=${{ env.ARM_GNU_ROOT }}/bin:$PATH
          make
        working-directory: "${{ github.workspace }}/targets/nrf52/"

      - name: Collect build artifacts 📂
        run: |
          mkdir -p content/nrf52/
          cp ${{ github.workspace }}/targets/nrf52/build/*.elf content/nrf52/ || true
          cp ${{ github.workspace }}/targets/nrf52/build/*.hex content/nrf52/ || true

      - name: Upload artifacts to GitHub 🔼
        uses: actions/upload-artifact@v4
        with:
          name: "nrf52"
          path: "content/nrf52/"